# Generated by Django 5.2.15 on 2026-06-17 11:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("kyc_approved", "KYC approved"),
                            ("kyc_rejected", "KYC rejected"),
                            ("kyb_approved", "KYB approved"),
                            ("kyb_rejected", "KYB rejected"),
                            ("wallet_created", "Wallet created"),
                            ("investment_minted", "Investment minted"),
                            ("earnings_credited", "Primary-sale earnings credited"),
                            ("distribution_credited", "Distribution credited"),
                            ("secondary_sale_buyer", "Secondary purchase settled"),
                            ("secondary_sale_seller", "Secondary sale settled"),
                            ("withdrawal_requested", "Withdrawal requested"),
                            ("submission_published", "Property submission published"),
                            ("submission_rejected", "Property submission rejected"),
                        ],
                        max_length=32,
                    ),
                ),
                ("params", models.JSONField(blank=True, default=dict)),
                (
                    "action_url",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("read", models.BooleanField(default=False)),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
                "db_table": "notifications",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["user", "read"], name="notificatio_user_id_1f75db_idx"
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="notificatio_user_id_7336fd_idx",
                    ),
                ],
            },
        ),
    ]
