# Generated by Django 5.2.15 on 2026-06-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("kyc_approved", "KYC approved"),
                    ("kyc_rejected", "KYC rejected"),
                    ("kyb_approved", "KYB approved"),
                    ("kyb_rejected", "KYB rejected"),
                    ("wallet_created", "Wallet created"),
                    ("investment_minted", "Investment minted"),
                    ("earnings_credited", "Primary-sale earnings credited"),
                    ("distribution_credited", "Distribution credited"),
                    ("secondary_sale_buyer", "Secondary purchase settled"),
                    ("secondary_sale_seller", "Secondary sale settled"),
                    ("withdrawal_requested", "Withdrawal requested"),
                    ("submission_published", "Property submission published"),
                    ("submission_rejected", "Property submission rejected"),
                    ("partner_assigned", "Assignment received"),
                    (
                        "partner_deliverable_submitted",
                        "Deliverable submitted (to admin)",
                    ),
                    ("partner_deliverable_approved", "Deliverable approved"),
                    ("partner_revision_requested", "Revision requested"),
                    ("partner_assignment_completed", "Assignment completed"),
                ],
                max_length=32,
            ),
        ),
    ]
