# Generated by Django 5.2.15 on 2026-06-23 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_profile_referred_by_broker"),
        ("notifications", "0006_alter_notification_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="notification_preference",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("distributions", models.BooleanField(default=True)),
                ("installments", models.BooleanField(default=True)),
                ("new_properties", models.BooleanField(default=True)),
                ("reports", models.BooleanField(default=True)),
                ("price_alerts", models.BooleanField(default=False)),
                ("market_updates", models.BooleanField(default=True)),
                ("security", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "notification preference",
                "verbose_name_plural": "notification preferences",
                "db_table": "notification_preferences",
            },
        ),
    ]
