# Generated by Django 5.2.15 on 2026-06-17 09:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wallets", "0004_withdrawal"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Distribution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("property_id", models.CharField(db_index=True, max_length=64)),
                (
                    "property_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "pool_amount_usd",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                ("dist_type", models.CharField(blank=True, default="", max_length=32)),
                (
                    "period_label",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("pay_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("paid", "Paid")],
                        db_index=True,
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "declared_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="declared_distributions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "distribution",
                "verbose_name_plural": "distributions",
                "db_table": "distributions",
                "ordering": ("-pay_date", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="DistributionPayout",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tokens_at_snapshot", models.PositiveIntegerField(default=0)),
                (
                    "ownership_pct_at_snapshot",
                    models.DecimalField(decimal_places=6, default=0, max_digits=12),
                ),
                (
                    "share_amount_usd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("credited", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "distribution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payouts",
                        to="distributions.distribution",
                    ),
                ),
                (
                    "holding",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="distribution_payouts",
                        to="wallets.ownershiptoken",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distribution_payouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "distribution payout",
                "verbose_name_plural": "distribution payouts",
                "db_table": "distribution_payouts",
                "ordering": ("-created_at",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("distribution", "user"),
                        name="uniq_payout_per_distribution_user",
                    )
                ],
            },
        ),
    ]
