# Generated by Django 5.2.15 on 2026-06-21 12:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("properties", "0004_property_submitted_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InstallmentPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("property_name", models.CharField(max_length=200)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=16)),
                (
                    "down_payment_amount",
                    models.DecimalField(decimal_places=2, max_digits=16),
                ),
                (
                    "down_payment_percent",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("number_of_installments", models.PositiveIntegerField()),
                (
                    "installment_amount",
                    models.DecimalField(decimal_places=2, max_digits=16),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("quarterly", "Quarterly")],
                        default="monthly",
                        max_length=12,
                    ),
                ),
                ("duration_months", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("defaulted", "Defaulted"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "investor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installment_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="installment_plans",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "installment plan",
                "verbose_name_plural": "installment plans",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="InstallmentPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                ("due_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=16)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("missed", "Missed"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="installments.installmentplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "installment payment",
                "verbose_name_plural": "installment payments",
                "ordering": ("plan", "sequence"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("plan", "sequence"),
                        name="uniq_installment_seq_per_plan",
                    )
                ],
            },
        ),
    ]
