# Generated by Django 5.2.15 on 2026-06-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("installments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="installmentplan",
            name="down_paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
