# Generated by Django 5.2.15 on 2026-06-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("installments", "0002_installmentplan_down_paid_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="installmentplan",
            name="defaulted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="installmentplan",
            name="forfeited_tokens",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="installmentpayment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("missed", "Missed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=12,
            ),
        ),
    ]
