# Generated by Django 5.2.15 on 2026-06-17 15:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BrokerProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("contact_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("suspended", "Suspended"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("applied_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                (
                    "license_number",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "license_authority",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("license_expiry", models.DateField(blank=True, null=True)),
                (
                    "license_document",
                    models.FileField(
                        blank=True, null=True, upload_to="broker_licenses/%Y/%m/"
                    ),
                ),
                ("license_submitted_at", models.DateTimeField(blank=True, null=True)),
                ("license_reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "review_notes",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "referral_code",
                    models.CharField(
                        blank=True, db_index=True, max_length=16, unique=True
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=5,
                        help_text="Percent commission (Wave B). Default 5%.",
                        max_digits=5,
                    ),
                ),
                (
                    "total_commission_earned",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "pending_commission",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="broker_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "broker profile",
                "verbose_name_plural": "broker profiles",
                "db_table": "broker_profiles",
                "ordering": ("-created_at",),
            },
        ),
    ]
