# Generated by Django 5.2.15 on 2026-06-25 09:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("broker", "0001_initial"),
        ("investments", "0002_investment_down_payment_amount_and_more"),
        ("wallets", "0005_deposit"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrokerCommission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "property_slug",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "property_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "gross",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "rate_applied",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The commission % stamped at conversion. Null = legacy row (rate not recorded).",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "commission",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "is_legacy",
                    models.BooleanField(
                        default=False,
                        help_text="True for backfilled rows reconstructed from a pre-existing BalanceTransaction.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "balance_transaction",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="broker_commission",
                        to="wallets.balancetransaction",
                    ),
                ),
                (
                    "broker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commissions",
                        to="broker.brokerprofile",
                    ),
                ),
                (
                    "investment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="broker_commissions",
                        to="investments.investment",
                    ),
                ),
            ],
            options={
                "verbose_name": "broker commission",
                "verbose_name_plural": "broker commissions",
                "db_table": "broker_commissions",
                "ordering": ("-created_at",),
            },
        ),
    ]
