# Generated by Django 5.2.15 on 2026-06-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="role_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("pending_verification", "Pending verification"),
                    ("suspended", "Suspended"),
                ],
                default="active",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="role_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("investor", "Investor"),
                    ("developer", "Developer"),
                    ("owner", "Owner"),
                    ("broker", "Broker"),
                    ("lp", "Liquidity Provider"),
                    ("partner", "Partner"),
                    ("admin", "Admin"),
                ],
                default="investor",
                max_length=16,
            ),
        ),
    ]
