# Generated by Django 5.2.15 on 2026-06-17 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("broker", "0001_initial"),
        ("core", "0002_profile_role_status_profile_role_verified_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="referred_by_broker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referred_profiles",
                to="broker.brokerprofile",
            ),
        ),
    ]
