# Generated by Django 5.2.15 on 2026-06-09 12:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserWallet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "wallet_address",
                    models.CharField(db_index=True, max_length=42, unique=True),
                ),
                (
                    "network",
                    models.CharField(
                        choices=[("bsc-testnet", "BSC Testnet")],
                        default="bsc-testnet",
                        max_length=24,
                    ),
                ),
                (
                    "wallet_type",
                    models.CharField(
                        choices=[("custodial", "Custodial")],
                        default="custodial",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "user wallet",
                "verbose_name_plural": "user wallets",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="WalletKeyMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("encrypted_private_key", models.TextField()),
                ("key_backend", models.CharField(max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "wallet",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="key_material",
                        to="wallets.userwallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "wallet key material",
                "verbose_name_plural": "wallet key material",
            },
        ),
    ]
