# Generated by Django 5.2.15 on 2026-06-09 16:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tx_hash", models.CharField(db_index=True, max_length=66)),
                ("tx_type", models.CharField(max_length=24)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                ("token_symbol", models.CharField(blank=True, max_length=16)),
                ("status", models.CharField(default="confirmed", max_length=16)),
                ("block_number", models.BigIntegerField(blank=True, null=True)),
                ("chain_id", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="wallets.userwallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "wallet transaction",
                "verbose_name_plural": "wallet transactions",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="OwnershipToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("property_id", models.CharField(db_index=True, max_length=64)),
                ("property_name", models.CharField(max_length=200)),
                ("token_symbol", models.CharField(max_length=16)),
                ("token_amount", models.PositiveIntegerField(default=0)),
                (
                    "token_value_usd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "ownership_percentage",
                    models.DecimalField(decimal_places=6, default=0, max_digits=12),
                ),
                ("acquisition_date", models.DateTimeField(auto_now_add=True)),
                ("last_distribution_date", models.DateTimeField(blank=True, null=True)),
                (
                    "total_distributions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("sold", "Sold")],
                        default="active",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ownership_tokens",
                        to="wallets.userwallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "ownership token",
                "verbose_name_plural": "ownership tokens",
                "ordering": ("-token_value_usd",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("wallet", "property_id"),
                        name="uniq_ownership_per_wallet_property",
                    )
                ],
            },
        ),
    ]
