# Generated by Django 5.2.15 on 2026-07-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0005_deposit"),
    ]

    operations = [
        migrations.AddField(
            model_name="deposit",
            name="target",
            field=models.CharField(
                choices=[
                    ("wallet", "Wallet balance"),
                    ("lp", "Liquidity Provider balance"),
                ],
                db_index=True,
                default="wallet",
                max_length=8,
            ),
        ),
    ]
