# Generated by Django 5.2.15 on 2026-07-12 07:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0006_deposit_target"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvestorBankAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bank_name", models.CharField(max_length=255)),
                ("bank_code", models.CharField(blank=True, max_length=64, null=True)),
                ("account_holder_name", models.CharField(max_length=255)),
                ("account_number_masked", models.CharField(max_length=64)),
                ("iban_masked", models.CharField(blank=True, max_length=64, null=True)),
                ("swift_code", models.CharField(blank=True, max_length=64, null=True)),
                ("country", models.CharField(max_length=120)),
                ("currency", models.CharField(max_length=8)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_default", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "investor bank account",
                "verbose_name_plural": "investor bank accounts",
                "ordering": ("-is_default", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="InvestorCryptoWallet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("wallet_address", models.CharField(max_length=255)),
                (
                    "wallet_label",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("network", models.CharField(max_length=64)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_default", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crypto_wallets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "investor crypto wallet",
                "verbose_name_plural": "investor crypto wallets",
                "ordering": ("-is_default", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="PaymentMethodAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action", models.CharField(max_length=16)),
                ("method_type", models.CharField(max_length=16)),
                ("method_id", models.UUIDField(blank=True, null=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_method_audit",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "payment method audit log",
                "verbose_name_plural": "payment method audit log",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="SavedCard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("card_brand", models.CharField(max_length=32)),
                ("card_last_four", models.CharField(max_length=4)),
                ("card_expiry_month", models.PositiveSmallIntegerField()),
                ("card_expiry_year", models.PositiveSmallIntegerField()),
                ("cardholder_name", models.CharField(max_length=255)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "saved card",
                "verbose_name_plural": "saved cards",
                "ordering": ("-is_default", "-created_at"),
            },
        ),
    ]
