# Generated by Django 5.2.15 on 2026-07-29 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0007_investorbankaccount_investorcryptowallet_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="withdrawal",
            name="bank_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="withdrawals",
                to="wallets.investorbankaccount",
            ),
        ),
        migrations.AddField(
            model_name="withdrawal",
            name="crypto_wallet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="withdrawals",
                to="wallets.investorcryptowallet",
            ),
        ),
        migrations.AddField(
            model_name="withdrawal",
            name="destination_label",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
