# Generated by Django 5.2.15 on 2026-08-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0008_withdrawal_bank_account_withdrawal_crypto_wallet_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deposit",
            name="proof_file",
            field=models.FileField(blank=True, null=True, upload_to="deposit_proofs/"),
        ),
        migrations.AddField(
            model_name="deposit",
            name="reference",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
