# Generated by Django 5.2.15 on 2026-06-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PWASettings",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("app_name", models.CharField(default="Capimax BRX", max_length=120)),
                ("app_short_name", models.CharField(default="Capimax", max_length=12)),
                (
                    "app_description",
                    models.CharField(
                        default="Real Estate Tokenization Platform", max_length=255
                    ),
                ),
                ("theme_color", models.CharField(default="#0f172a", max_length=9)),
                ("background_color", models.CharField(default="#ffffff", max_length=9)),
                ("install_prompt_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "PWA settings",
                "verbose_name_plural": "PWA settings",
                "db_table": "pwa_settings",
            },
        ),
    ]
