# Generated by Django 5.2.15 on 2026-06-15 09:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LiquidityProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("contact_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40, null=True)),
                ("country", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "investment_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("suspended", "Suspended"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("applied_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rejection_reason",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("bank_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "bank_account_number",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("bank_iban", models.CharField(blank=True, max_length=64, null=True)),
                ("bank_swift", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "crypto_wallet_address",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "crypto_network",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "total_deposited",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "total_withdrawn",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "total_earnings",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "current_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "kyb_status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not started"),
                            ("documents_pending", "Documents pending"),
                            ("under_review", "Under review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="not_started",
                        max_length=20,
                    ),
                ),
                (
                    "business_type",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "business_registration_number",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("tax_id", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "business_address",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("business_description", models.TextField(blank=True, null=True)),
                (
                    "annual_revenue",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "source_of_funds",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "sumsub_applicant_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "sumsub_review_answer",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                ("kyb_submitted_at", models.DateTimeField(blank=True, null=True)),
                ("kyb_approved_at", models.DateTimeField(blank=True, null=True)),
                ("kyb_rejected_at", models.DateTimeField(blank=True, null=True)),
                (
                    "kyb_rejection_reason",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liquidity_provider",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "liquidity provider",
                "verbose_name_plural": "liquidity providers",
                "db_table": "liquidity_providers",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="LPDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("document_name", models.CharField(max_length=255)),
                ("document_type", models.CharField(max_length=64)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="lp_documents/%Y/%m/"
                    ),
                ),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("is_template", models.BooleanField(default=False)),
                ("uploaded_by", models.CharField(default="user", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lp",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="lp.liquidityprovider",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lp_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "LP document",
                "verbose_name_plural": "LP documents",
                "db_table": "lp_documents",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="LPKYBDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("document_name", models.CharField(max_length=255)),
                ("document_type", models.CharField(max_length=64)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="lp_kyb_documents/%Y/%m/"
                    ),
                ),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                (
                    "rejection_reason",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyb_documents",
                        to="lp.liquidityprovider",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lp_kyb_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "LP KYB document",
                "verbose_name_plural": "LP KYB documents",
                "db_table": "lp_kyb_documents",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="LPTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tx_type", models.CharField(max_length=32)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("currency", models.CharField(default="USD", max_length=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                (
                    "withdrawal_method",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                (
                    "bank_reference",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "crypto_tx_hash",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("notes", models.CharField(blank=True, max_length=500, null=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="lp.liquidityprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "LP transaction",
                "verbose_name_plural": "LP transactions",
                "db_table": "lp_transactions",
                "ordering": ("-created_at",),
            },
        ),
    ]
