# Generated by Django 5.2.15 on 2026-06-15 10:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LPMarketListing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("property_id", models.CharField(db_index=True, max_length=64)),
                ("property_name", models.CharField(max_length=200)),
                ("token_symbol", models.CharField(max_length=16)),
                ("token_amount", models.PositiveIntegerField()),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=100, max_digits=16),
                ),
                ("total_value", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "platform_fee_percent",
                    models.DecimalField(decimal_places=3, default=1, max_digits=6),
                ),
                (
                    "platform_fee_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "net_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("listed", "Listed"),
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="listed",
                        max_length=12,
                    ),
                ),
                (
                    "settlement_tx_hash",
                    models.CharField(blank=True, default="", max_length=66),
                ),
                ("listed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("purchased_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lp",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchases",
                        to="lp.liquidityprovider",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lp_market_listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "LP market listing",
                "verbose_name_plural": "LP market listings",
                "db_table": "lp_market_listings",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="LPHolding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("property_id", models.CharField(db_index=True, max_length=64)),
                ("property_name", models.CharField(max_length=200)),
                ("token_symbol", models.CharField(max_length=16)),
                ("token_amount", models.PositiveIntegerField()),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                ("current_value", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "purchase_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("held", "Held"),
                            ("listed_lp", "Listed (LP)"),
                            ("listed_secondary", "Listed (secondary)"),
                            ("sold", "Sold"),
                        ],
                        db_index=True,
                        default="held",
                        max_length=20,
                    ),
                ),
                ("listed_at", models.DateTimeField(blank=True, null=True)),
                ("sold_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holdings",
                        to="lp.liquidityprovider",
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resulting_holdings",
                        to="lp.lpmarketlisting",
                    ),
                ),
            ],
            options={
                "verbose_name": "LP holding",
                "verbose_name_plural": "LP holdings",
                "db_table": "lp_holdings",
                "ordering": ("-purchase_date",),
            },
        ),
    ]
