# Generated by Django 5.2.15 on 2026-06-08 16:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("name_ar", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=200)),
                ("location_ar", models.CharField(max_length=200)),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("uae", "UAE"),
                            ("ksa", "KSA"),
                            ("qatar", "Qatar"),
                            ("bahrain", "Bahrain"),
                            ("oman", "Oman"),
                        ],
                        max_length=16,
                    ),
                ),
                ("city", models.CharField(max_length=80)),
                ("image", models.URLField(max_length=500)),
                ("images", models.JSONField(blank=True, default=list)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("residential", "Residential"),
                            ("commercial", "Commercial"),
                            ("industrial", "Industrial"),
                            ("mixed", "Mixed"),
                            ("hospitality", "Hospitality"),
                            ("land", "Land"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        choices=[
                            ("ready", "Ready Property"),
                            ("ready_portfolio", "Ready Portfolio"),
                            ("installment", "Installment"),
                            ("phasing", "Phasing"),
                            ("future", "Future"),
                            ("option", "Option"),
                            ("shared", "Shared with Owner"),
                            ("construction_portfolio", "Construction Portfolio"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ready", "Ready"),
                            ("construction", "Construction"),
                            ("ready_portfolio", "Ready Portfolio"),
                            ("construction_portfolio", "Construction Portfolio"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ready", "Ready"),
                            ("construction", "Under Construction"),
                            ("sold-out", "Sold Out"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "yield_type",
                    models.CharField(
                        choices=[
                            ("rental", "Rental"),
                            ("appreciation", "Appreciation"),
                            ("hybrid", "Hybrid"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=8,
                    ),
                ),
                ("total_value", models.DecimalField(decimal_places=2, max_digits=16)),
                (
                    "token_price",
                    models.DecimalField(decimal_places=2, default=100, max_digits=12),
                ),
                ("token_supply", models.PositiveIntegerField(default=0)),
                (
                    "future_token_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "expected_yield",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "expected_growth",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("funded", models.PositiveSmallIntegerField(default=0)),
                ("investors", models.PositiveIntegerField(default=0)),
                (
                    "min_investment",
                    models.DecimalField(decimal_places=2, default=100, max_digits=12),
                ),
                ("duration", models.CharField(max_length=40)),
                ("duration_ar", models.CharField(max_length=40)),
                ("exit_eligible", models.BooleanField(default=False)),
                (
                    "exit_availability",
                    models.CharField(
                        choices=[
                            ("lp", "LP Market"),
                            ("secondary", "Secondary Market"),
                            ("both", "Both"),
                            ("none", "None"),
                        ],
                        max_length=16,
                    ),
                ),
                ("insurance_active", models.BooleanField(default=False)),
                ("description", models.TextField()),
                ("description_ar", models.TextField()),
                (
                    "construction_progress",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "fee_platform",
                    models.DecimalField(decimal_places=2, default=1.5, max_digits=5),
                ),
                (
                    "fee_management",
                    models.DecimalField(decimal_places=2, default=0.5, max_digits=5),
                ),
                (
                    "fee_exit",
                    models.DecimalField(decimal_places=2, default=0.5, max_digits=5),
                ),
                ("is_published", models.BooleanField(db_index=True, default=True)),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("funded_date", models.DateField(blank=True, null=True)),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "property",
                "verbose_name_plural": "properties",
                "ordering": ("display_order", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="PortfolioAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset_slug", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=120)),
                ("name_ar", models.CharField(max_length=120)),
                ("city", models.CharField(max_length=80)),
                ("weight", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("residential", "Residential"),
                            ("commercial", "Commercial"),
                            ("industrial", "Industrial"),
                            ("mixed", "Mixed"),
                            ("hospitality", "Hospitality"),
                            ("land", "Land"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio_assets",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="OptionContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "option_premium",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("strike_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("expiry_date", models.DateField()),
                ("validity_months", models.PositiveIntegerField()),
                (
                    "estimated_future_value",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("exercise_conditions", models.TextField()),
                ("exercise_conditions_ar", models.TextField()),
                (
                    "property",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="option",
                        to="properties.property",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InstallmentSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_installments", models.PositiveIntegerField()),
                ("paid_installments", models.PositiveIntegerField(default=0)),
                (
                    "monthly_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("next_payment_date", models.DateField()),
                ("activation_date", models.DateField()),
                (
                    "completion_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "property",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installment",
                        to="properties.property",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FutureContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reservation_date", models.DateField()),
                ("activation_date", models.DateField()),
                ("settlement_date", models.DateField()),
                (
                    "reservation_price",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "estimated_future_value",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("estimated_roi", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "property",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="future",
                        to="properties.property",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeveloperReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("title", models.CharField(max_length=200)),
                ("title_ar", models.CharField(max_length=200)),
                ("progress", models.PositiveSmallIntegerField(default=0)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="developer_reports",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "ordering": ("-date",),
            },
        ),
        migrations.CreateModel(
            name="PropertyDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("name_en", models.CharField(max_length=200)),
                ("date", models.DateField()),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("valuation", "Valuation"),
                            ("legal", "Legal"),
                            ("insurance", "Insurance"),
                            ("financial", "Financial"),
                            ("construction", "Construction"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "ordering": ("-date",),
            },
        ),
        migrations.CreateModel(
            name="PropertyFinancials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "current_valuation",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "gross_rental_income",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "operating_expenses",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "net_operating_income",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "cap_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "occupancy_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "property",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financials",
                        to="properties.property",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PropertyPhase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=120)),
                ("name_ar", models.CharField(max_length=120)),
                ("token_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("current", "Current"),
                            ("upcoming", "Upcoming"),
                        ],
                        max_length=16,
                    ),
                ),
                ("progress", models.PositiveSmallIntegerField(default=0)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phases",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "ordering": ("number",),
            },
        ),
        migrations.CreateModel(
            name="SharedOwnership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("investor_share", models.DecimalField(decimal_places=2, max_digits=5)),
                ("owner_share", models.DecimalField(decimal_places=2, max_digits=5)),
                ("owner_name", models.CharField(max_length=200)),
                ("profit_split", models.CharField(max_length=120)),
                (
                    "revenue_distribution",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("annual", "Annual"),
                        ],
                        max_length=16,
                    ),
                ),
                ("transfer_process", models.TextField()),
                ("transfer_process_ar", models.TextField()),
                (
                    "property",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared",
                        to="properties.property",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SPVRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("jurisdiction", models.CharField(max_length=120)),
                ("registration_number", models.CharField(max_length=120)),
                ("established", models.DateField(blank=True, null=True)),
                (
                    "property",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spv",
                        to="properties.property",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TokenMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contract_address", models.CharField(blank=True, max_length=120)),
                ("network", models.CharField(default="Ethereum", max_length=40)),
                ("network_icon", models.CharField(blank=True, max_length=8)),
                ("standard", models.CharField(default="ERC-1155", max_length=40)),
                ("total_supply", models.PositiveIntegerField(default=0)),
                ("tokenized_units", models.PositiveIntegerField(default=0)),
                (
                    "token_price",
                    models.DecimalField(decimal_places=2, default=100, max_digits=12),
                ),
                ("verified", models.BooleanField(default=True)),
                ("deployed_date", models.DateField(blank=True, null=True)),
                ("explorer_url", models.URLField(blank=True, max_length=500)),
                (
                    "property",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="token_metadata",
                        to="properties.property",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ValuationReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("valuation", models.DecimalField(decimal_places=2, max_digits=16)),
                ("appraiser", models.CharField(max_length=120)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valuation_reports",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "ordering": ("-date",),
            },
        ),
    ]
