# Generated by Django 5.2.15 on 2026-06-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tokenmetadata",
            name="deployed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tokenmetadata",
            name="deployed_contract_address",
            field=models.CharField(blank=True, max_length=42),
        ),
        migrations.AddField(
            model_name="tokenmetadata",
            name="deployment_chain_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tokenmetadata",
            name="deployment_network",
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name="tokenmetadata",
            name="deployment_tx",
            field=models.CharField(blank=True, max_length=66),
        ),
        migrations.AddField(
            model_name="tokenmetadata",
            name="factory_address",
            field=models.CharField(blank=True, max_length=42),
        ),
    ]
