# Generated by Django 5.2.15 on 2026-06-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0004_property_submitted_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="broker_commission_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=5,
                help_text="Per-property broker commission %. Null → fall back to the broker's own rate.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="open_for_promotion",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
