# Generated by Django 5.2.15 on 2026-07-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0005_property_broker_commission_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="fee_pronova_discount",
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
    ]
