# Generated by Django 5.2.15 on 2026-08-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0006_property_fee_pronova_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertydocument",
            name="url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="property",
            name="country",
            field=models.CharField(
                choices=[
                    ("uae", "UAE"),
                    ("ksa", "KSA"),
                    ("qatar", "Qatar"),
                    ("bahrain", "Bahrain"),
                    ("oman", "Oman"),
                    ("uk", "United Kingdom"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="propertydocument",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("valuation", "Valuation"),
                    ("legal", "Legal"),
                    ("insurance", "Insurance"),
                    ("financial", "Financial"),
                    ("construction", "Construction"),
                    ("studies", "Studies"),
                    ("brochure", "Brochure"),
                    ("tokenization", "Tokenization Agreement"),
                    ("lease", "Lease Agreement"),
                    ("audit", "Smart Contract Audit"),
                    ("diligence", "Due Diligence"),
                ],
                max_length=16,
            ),
        ),
    ]
