# Generated by Django 5.2.15 on 2026-08-13 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0007_propertydocument_url_alter_property_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tokenmetadata",
            name="investor_allocation",
            field=models.PositiveSmallIntegerField(default=85),
        ),
        migrations.AddField(
            model_name="tokenmetadata",
            name="liquidity",
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name="tokenmetadata",
            name="platform_incentive",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="tokenmetadata",
            name="spv_reserve",
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_en", models.CharField(max_length=120)),
                ("name_ar", models.CharField(blank=True, max_length=120)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amenities",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="DeveloperInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("name_ar", models.CharField(blank=True, max_length=200)),
                ("overview", models.TextField(blank=True)),
                ("overview_ar", models.TextField(blank=True)),
                ("years_experience", models.PositiveIntegerField(default=0)),
                ("completed_projects", models.PositiveIntegerField(default=0)),
                ("ongoing_projects", models.PositiveIntegerField(default=0)),
                (
                    "rating",
                    models.DecimalField(decimal_places=1, default=0, max_digits=3),
                ),
                ("location", models.CharField(blank=True, max_length=200)),
                ("location_ar", models.CharField(blank=True, max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("related_projects", models.JSONField(blank=True, default=list)),
                (
                    "property",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="developer_info",
                        to="properties.property",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InsuranceInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=200)),
                ("policy_number", models.CharField(blank=True, max_length=80)),
                (
                    "coverage_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                ("reinsurer", models.CharField(blank=True, max_length=200)),
                ("valuation_firm", models.CharField(blank=True, max_length=200)),
                (
                    "property",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insurance_info",
                        to="properties.property",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Landmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_en", models.CharField(max_length=160)),
                ("name_ar", models.CharField(blank=True, max_length=160)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="landmarks",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="MarketData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cap_rate", models.CharField(blank=True, max_length=16)),
                ("city_growth", models.CharField(blank=True, max_length=16)),
                ("vacancy_rate", models.CharField(blank=True, max_length=16)),
                ("rent_index", models.CharField(blank=True, max_length=16)),
                ("price_index_history", models.JSONField(blank=True, default=list)),
                (
                    "property",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_data",
                        to="properties.property",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PropertyFAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_en", models.CharField(max_length=300)),
                ("question_ar", models.CharField(blank=True, max_length=300)),
                ("answer_en", models.TextField()),
                ("answer_ar", models.TextField(blank=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faqs",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="RiskFactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_en", models.CharField(max_length=300)),
                ("text_ar", models.CharField(blank=True, max_length=300)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_factors",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
    ]
