# Generated by Django 5.2.15 on 2026-06-09 16:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("certificate_id", models.CharField(max_length=40, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("provisional", "Provisional"),
                            ("final", "Final"),
                            ("revoked", "Revoked"),
                        ],
                        default="provisional",
                        max_length=12,
                    ),
                ),
                ("issue_date", models.DateField(auto_now_add=True)),
                ("subscription_date", models.DateField(blank=True, null=True)),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                ("investor_name", models.CharField(blank=True, max_length=200)),
                ("investor_id_masked", models.CharField(blank=True, max_length=64)),
                ("spv_name", models.CharField(blank=True, max_length=200)),
                ("spv_registration_ref", models.CharField(blank=True, max_length=120)),
                ("property_name", models.CharField(blank=True, max_length=200)),
                ("property_location", models.CharField(blank=True, max_length=200)),
                ("listing_id", models.CharField(blank=True, max_length=64)),
                (
                    "investment_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                ("units_purchased", models.PositiveIntegerField(default=0)),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "ownership_percentage",
                    models.DecimalField(decimal_places=6, default=0, max_digits=12),
                ),
                (
                    "platform_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                ("authorized_signatory", models.CharField(blank=True, max_length=200)),
                (
                    "digital_signature_hash",
                    models.CharField(blank=True, max_length=128),
                ),
                ("qr_code_data", models.TextField(blank=True)),
                (
                    "verification_code",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("verification_url", models.CharField(blank=True, max_length=300)),
                ("pdf_url", models.CharField(blank=True, max_length=500)),
                ("pdf_path", models.CharField(blank=True, max_length=500)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revocation_reason", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "certificate",
                "verbose_name_plural": "certificates",
                "ordering": ("-issue_date",),
            },
        ),
    ]
