# Generated by Django 5.2.15 on 2026-06-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="pdf_file",
            field=models.FileField(
                blank=True, null=True, upload_to="certificates/%Y/%m/"
            ),
        ),
    ]
