# Generated by Django 5.2.15 on 2026-06-16 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("owner", "0002_propertysubmission_submissiondocument"),
        ("properties", "0004_property_submitted_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertysubmission",
            name="published_property",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="properties.property",
            ),
        ),
        migrations.AddField(
            model_name="propertysubmission",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
