# Generated by Django 5.2.15 on 2026-06-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("owner", "0003_propertysubmission_published_property_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertysubmission",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="propertysubmission",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="propertysubmission",
            name="virtual_tour_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="submissiondocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("title", "Title Deed"),
                    ("valuation", "Valuation Report"),
                    ("insurance", "Insurance Policy"),
                    ("noc", "NOC"),
                    ("financial", "Financial Statements"),
                    ("legal", "Legal Documents"),
                    ("image", "Property Image"),
                    ("video", "Property Video"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=32,
            ),
        ),
    ]
