import { MainLayout } from "@/components/layout/MainLayout";
import { useLanguage } from "@/contexts/LanguageContext";
import { Button } from "@/components/ui/button";
import { ShieldCheck, ExternalLink, BadgeCheck, Building2, Landmark, Scale, FileCheck } from "lucide-react";

/**
 * Verification Center — a GATEWAY page, not a verification engine.
 *
 * Group policy: every Capimax platform (BRX, RT, PropShare, Asset, Nova) exposes a single
 * "Verification Center" that routes the user to Capimax Trust (www.capimax.pro), the ONE
 * central authority that verifies every document/certificate/record in the ecosystem. We
 * deliberately do NOT build a verification system inside BRX — this page only introduces the
 * concept and hands off to Capimax Trust, where the user verifies authenticity, reviews a
 * document's status, and downloads the official copy.
 *
 * NOTE: the official Capimax Trust logo + the intro clip weren't supplied yet — the logo here
 * is a branded placeholder (swap the block below for the real asset) and the clip slot is
 * omitted until the file is provided.
 */
const TRUST_URL = "https://www.capimax.pro";

export default function VerificationCenter() {
  const { language } = useLanguage();
  const isAr = language === "ar";

  // Issuers whose documents Capimax Trust can verify — shown as a quick trust-signal row.
  const issuers = [
    { icon: BadgeCheck, en: "Valuation firms", ar: "شركات التقييم" },
    { icon: ShieldCheck, en: "Insurance providers", ar: "شركات التأمين" },
    { icon: Scale, en: "Legal advisors", ar: "المكاتب القانونية" },
    { icon: FileCheck, en: "Auditors", ar: "المدققون" },
    { icon: Building2, en: "Financial institutions", ar: "المؤسسات المالية" },
    { icon: Landmark, en: "Government authorities", ar: "الجهات الحكومية" },
  ];

  return (
    <MainLayout>
      <div className="min-h-screen bg-background">
        {/* Hero */}
        <div className="relative overflow-hidden border-b border-border">
          <div className="absolute inset-0 bg-gradient-to-b from-primary/10 via-background to-background" />
          <div className="container relative py-16 sm:py-20">
            <div className="max-w-3xl mx-auto text-center space-y-6">
              <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full border border-primary/30 bg-primary/5 text-primary text-sm font-medium">
                <ShieldCheck className="w-4 h-4" />
                {isAr ? "التحقق الموثّق" : "Trusted Verification"}
              </div>

              <h1 className="font-display text-4xl sm:text-5xl font-bold text-foreground">
                {isAr ? "مركز التحقق" : "Verification Center"}
              </h1>

              <p className="text-lg text-muted-foreground leading-relaxed">
                {isAr
                  ? "جميع المستندات والشهادات والسجلات الصادرة من هذه المنصة — سواء من منظومة Capimax أو من جهات خارجية مثل شركات التقييم وشركات التأمين والمكاتب القانونية والمدققين والمؤسسات المالية والجهات الحكومية — يمكن التحقق منها، واستعراض حالتها، وتحميل النسخة الرسمية منها من خلال منصة Capimax Trust."
                  : "All documents, certificates, and records issued through this platform — including those generated by the Capimax ecosystem as well as documents issued by external organizations such as valuation firms, insurance providers, legal advisors, auditors, financial institutions, and government authorities — can be verified, their status reviewed, and official copies downloaded through the Capimax Trust platform."}
              </p>
            </div>
          </div>
        </div>

        <div className="container py-12 sm:py-16">
          <div className="max-w-3xl mx-auto space-y-10">
            {/* Capimax Trust gateway card */}
            <div className="rounded-3xl border border-border bg-card p-8 sm:p-12 text-center shadow-sm">
              {/* Brand logo — PLACEHOLDER. Replace this block with the official Capimax Trust logo. */}
              <div className="mx-auto mb-6 flex flex-col items-center gap-4">
                <div className="w-24 h-24 rounded-2xl bg-gradient-to-br from-primary to-primary/70 flex items-center justify-center shadow-lg shadow-primary/20">
                  <ShieldCheck className="w-12 h-12 text-primary-foreground" strokeWidth={1.75} />
                </div>
                <div>
                  <div className="font-display text-2xl font-bold text-foreground tracking-tight">
                    Capimax <span className="text-primary">Trust</span>
                  </div>
                  <div className="text-xs uppercase tracking-[0.2em] text-muted-foreground mt-1">
                    {isAr ? "بوابة التحقق المركزية" : "Central Verification Gateway"}
                  </div>
                </div>
              </div>

              <p className="text-muted-foreground leading-relaxed max-w-xl mx-auto">
                {isAr
                  ? "تُمثّل منصة Capimax Trust بوابة التحقق المركزية لمنظومة Capimax، وتوفّر مصدرًا آمنًا وموثوقًا للتحقق من صحة وسلامة المستندات المسجّلة."
                  : "Capimax Trust serves as the central verification gateway for the Capimax ecosystem, providing a secure and trusted source for validating the authenticity and integrity of registered documents."}
              </p>

              {/* Primary CTA → external hand-off to Capimax Trust */}
              <div className="mt-8 flex flex-col items-center gap-3">
                <Button asChild variant="hero" size="xl" className="min-w-[260px]">
                  <a href={TRUST_URL} target="_blank" rel="noopener noreferrer">
                    <ShieldCheck className="w-5 h-5" />
                    {isAr ? "التحقق من المستندات" : "Verify Documents"}
                    <ExternalLink className="w-4 h-4 opacity-80" />
                  </a>
                </Button>
                <a
                  href={TRUST_URL}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-sm text-primary hover:underline"
                >
                  {isAr ? "اضغط هنا للتحقق — www.capimax.pro" : "Click here to verify — www.capimax.pro"}
                </a>
              </div>
            </div>

            {/* What you can do on Capimax Trust */}
            <div className="grid gap-4 sm:grid-cols-2">
              {[
                {
                  en: "Verify document authenticity",
                  ar: "التحقق من صحة المستندات",
                },
                { en: "Review a document's status", ar: "استعراض حالة المستند" },
                { en: "Download the official copy", ar: "تحميل النسخة الرسمية" },
                { en: "View the document's verification data", ar: "الاطلاع على بيانات التحقق" },
              ].map((item) => (
                <div
                  key={item.en}
                  className="flex items-start gap-3 rounded-xl border border-border bg-card/50 p-4"
                >
                  <BadgeCheck className="w-5 h-5 text-primary shrink-0 mt-0.5" />
                  <span className="text-sm text-foreground">{isAr ? item.ar : item.en}</span>
                </div>
              ))}
            </div>

            {/* Recognised issuers */}
            <div className="space-y-4">
              <h2 className="font-display text-lg font-semibold text-foreground text-center">
                {isAr ? "مستندات من داخل وخارج المنظومة" : "Documents from inside and outside the ecosystem"}
              </h2>
              <div className="flex flex-wrap justify-center gap-2">
                {issuers.map((it) => (
                  <span
                    key={it.en}
                    className="inline-flex items-center gap-2 rounded-full border border-border bg-card px-4 py-2 text-sm text-muted-foreground"
                  >
                    <it.icon className="w-4 h-4 text-primary" />
                    {isAr ? it.ar : it.en}
                  </span>
                ))}
              </div>
            </div>

            <p className="text-center text-xs text-muted-foreground">
              {isAr
                ? "جميع عمليات التحقق تتم حصريًا من خلال منصة Capimax Trust."
                : "All verification is performed exclusively through the Capimax Trust platform."}
            </p>
          </div>
        </div>
      </div>
    </MainLayout>
  );
}
