# Generated by Django 5.2.15 on 2026-06-15 16:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SecondaryMarketListing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "seller_type",
                    models.CharField(
                        choices=[
                            ("investor", "Investor"),
                            ("lp", "Liquidity Provider"),
                        ],
                        default="investor",
                        max_length=12,
                    ),
                ),
                (
                    "buyer_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("investor", "Investor"),
                            ("lp", "Liquidity Provider"),
                        ],
                        default="",
                        max_length=12,
                    ),
                ),
                ("property_id", models.CharField(db_index=True, max_length=64)),
                ("property_name", models.CharField(max_length=200)),
                ("token_symbol", models.CharField(max_length=16)),
                ("token_amount", models.PositiveIntegerField()),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=100, max_digits=16),
                ),
                ("total_value", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "platform_fee_percent",
                    models.DecimalField(decimal_places=3, default=0.5, max_digits=6),
                ),
                (
                    "platform_fee_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "net_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("listed", "Listed"),
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="listed",
                        max_length=12,
                    ),
                ),
                (
                    "settlement_tx_hash",
                    models.CharField(blank=True, default="", max_length=66),
                ),
                ("listed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("purchased_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="secondary_market_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secondary_market_listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "secondary market listing",
                "verbose_name_plural": "secondary market listings",
                "db_table": "secondary_market_listings",
                "ordering": ("-created_at",),
            },
        ),
    ]
