# Generated by Django 5.2.15 on 2026-06-17 14:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("contact_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("suspended", "Suspended"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("applied_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rejection_reason",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "kyb_status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not started"),
                            ("documents_pending", "Documents pending"),
                            ("under_review", "Under review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="not_started",
                        max_length=20,
                    ),
                ),
                (
                    "business_type",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "business_registration_number",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("tax_id", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "business_address",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("business_description", models.TextField(blank=True, null=True)),
                (
                    "sumsub_applicant_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "sumsub_review_answer",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                ("kyb_submitted_at", models.DateTimeField(blank=True, null=True)),
                ("kyb_approved_at", models.DateTimeField(blank=True, null=True)),
                ("kyb_rejected_at", models.DateTimeField(blank=True, null=True)),
                (
                    "kyb_rejection_reason",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "company_name_ar",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("developers", "Developers"),
                            ("hotels", "Hotels"),
                            ("property-management", "Property Management"),
                            ("insurance", "Insurance"),
                            ("valuation", "Valuation"),
                            ("digital-finance", "Digital Finance"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("description_ar", models.TextField(blank=True, null=True)),
                ("logo_url", models.URLField(blank=True, max_length=500, null=True)),
                ("country", models.CharField(blank=True, max_length=120, null=True)),
                ("country_ar", models.CharField(blank=True, max_length=120, null=True)),
                ("website", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "directory_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("directory_reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "directory_review_notes",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "partner profile",
                "verbose_name_plural": "partner profiles",
                "db_table": "partner_profiles",
                "ordering": ("-created_at",),
            },
        ),
    ]
