# Generated by Django 5.2.15 on 2026-06-17 14:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0001_initial"),
        ("properties", "0004_property_submitted_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "property_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "property_name_ar",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("location", models.CharField(blank=True, default="", max_length=200)),
                (
                    "location_ar",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("valuation", "Valuation"),
                            ("property-management", "Property Management"),
                            ("insurance", "Insurance"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in-progress", "In progress"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("revision", "Revision requested"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("review_notes", models.TextField(blank=True, default="")),
                (
                    "assigned_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="partners.partnerprofile",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="partner_assignments",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "partner assignment",
                "verbose_name_plural": "partner assignments",
                "db_table": "partner_assignments",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="AssignmentEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("uploaded", "Deliverable uploaded"),
                            ("submitted", "Submitted for review"),
                            ("approved", "Deliverable approved"),
                            ("revision_requested", "Revision requested"),
                            ("completed", "All deliverables completed"),
                        ],
                        max_length=24,
                    ),
                ),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="partners.assignment",
                    ),
                ),
            ],
            options={
                "verbose_name": "assignment event",
                "verbose_name_plural": "assignment events",
                "db_table": "partner_assignment_events",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Deliverable",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("name_ar", models.CharField(blank=True, default="", max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("revision", "Revision requested"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliverables",
                        to="partners.assignment",
                    ),
                ),
            ],
            options={
                "verbose_name": "deliverable",
                "verbose_name_plural": "deliverables",
                "db_table": "partner_deliverables",
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="DeliverableDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="deliverable_documents/%Y/%m/"
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="partners.assignment",
                    ),
                ),
                (
                    "deliverable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="partners.deliverable",
                    ),
                ),
            ],
            options={
                "verbose_name": "deliverable document",
                "verbose_name_plural": "deliverable documents",
                "db_table": "deliverable_documents",
                "ordering": ("-uploaded_at",),
            },
        ),
    ]
