# Generated by Django 5.2.15 on 2026-06-29 12:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0002_assignment_assignmentevent_deliverable_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerKYBDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("document_name", models.CharField(max_length=255)),
                ("document_type", models.CharField(max_length=64)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="partner_kyb_documents/%Y/%m/"
                    ),
                ),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                (
                    "rejection_reason",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyb_documents",
                        to="partners.partnerprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner_kyb_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "partner KYB document",
                "verbose_name_plural": "partner KYB documents",
                "db_table": "partner_kyb_documents",
                "ordering": ("-created_at",),
            },
        ),
    ]
