# Generated by Django 5.2.15 on 2026-06-09 16:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("properties", "0002_tokenmetadata_deployed_at_and_more"),
        ("wallets", "0002_wallettransaction_ownershiptoken"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Investment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("property_name", models.CharField(max_length=200)),
                (
                    "amount_invested",
                    models.DecimalField(decimal_places=2, max_digits=16),
                ),
                ("token_amount", models.PositiveIntegerField()),
                ("token_symbol", models.CharField(max_length=16)),
                (
                    "price_per_token",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "ownership_percentage",
                    models.DecimalField(decimal_places=6, max_digits=12),
                ),
                ("payment_method", models.CharField(max_length=24)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("tokens_minted", models.BooleanField(default=False)),
                ("minted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="investments",
                        to="properties.property",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="investments",
                        to="wallets.userwallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "investment",
                "verbose_name_plural": "investments",
                "ordering": ("-created_at",),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("payment_status__in", ["pending", "processing"])
                        ),
                        fields=("user", "property"),
                        name="uniq_active_investment_per_user_property",
                    )
                ],
            },
        ),
    ]
