# Generated by Django 5.2.15 on 2026-06-21 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("installments", "0002_installmentplan_down_paid_at"),
        ("investments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="investment",
            name="down_payment_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=16, null=True
            ),
        ),
        migrations.AddField(
            model_name="investment",
            name="installment_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="investments",
                to="installments.installmentplan",
            ),
        ),
        migrations.AddField(
            model_name="investment",
            name="is_installment",
            field=models.BooleanField(default=False),
        ),
    ]
