# Generated by Django 5.2.15 on 2026-07-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investments", "0002_investment_down_payment_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="investment",
            name="fee_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
