# Generated by Django 5.2.15 on 2026-07-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investments", "0003_investment_fee_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="investment",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
