# Generated by Django 5.2.15 on 2026-06-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="nowpayments_payment_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="pay_address",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="payment",
            name="pay_amount",
            field=models.DecimalField(
                blank=True, decimal_places=18, max_digits=36, null=True
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="pay_currency",
            field=models.CharField(blank=True, default="", max_length=24),
        ),
    ]
