# Generated by Django 5.2.15 on 2026-06-22 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("installments", "0002_installmentplan_down_paid_at"),
        (
            "payments",
            "0002_payment_nowpayments_payment_id_payment_pay_address_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="installment_payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="installments.installmentpayment",
            ),
        ),
    ]
