# Generated by Django 5.2.15 on 2026-06-23 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investments", "0002_investment_down_payment_amount_and_more"),
        ("payments", "0003_payment_installment_payment"),
        ("wallets", "0005_deposit"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="deposit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="wallets.deposit",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="investment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="investments.investment",
            ),
        ),
    ]
