# Generated by Django 5.2.15 on 2026-07-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_payment_deposit_alter_payment_investment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="is_installment_payoff",
            field=models.BooleanField(default=False),
        ),
    ]
