# Generated by Django 5.2.15 on 2026-07-05 09:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investments", "0003_investment_fee_amount"),
        ("payments", "0005_payment_is_installment_payoff"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SukukCertificate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(upload_to="sukuk_certificates/%Y/%m/")),
                ("file_size", models.PositiveIntegerField(blank=True, null=True)),
                ("file_type", models.CharField(blank=True, default="", max_length=100)),
                ("sukuk_id", models.CharField(blank=True, default="", max_length=100)),
                ("issuer", models.CharField(blank=True, default="", max_length=200)),
                (
                    "claimed_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                ("validity_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                (
                    "review_notes",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "investment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sukuk_certificate",
                        to="investments.investment",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "sukuk certificate",
                "verbose_name_plural": "sukuk certificates",
                "ordering": ("-created_at",),
            },
        ),
    ]
