# Generated by Django 5.2.15 on 2026-06-22 11:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FamilyAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("member_name", models.CharField(max_length=200)),
                ("member_email", models.EmailField(max_length=254)),
                ("relationship", models.CharField(max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=12,
                    ),
                ),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("view_only", "View only"),
                            ("authorized", "Authorized"),
                        ],
                        default="view_only",
                        max_length=12,
                    ),
                ),
                (
                    "allocated_returns_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "total_transferred",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                ("linked_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "investor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "family account",
                "verbose_name_plural": "family accounts",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="FamilyBankAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bank_name", models.CharField(max_length=120)),
                ("bank_code", models.CharField(blank=True, default="", max_length=40)),
                ("account_holder_name", models.CharField(max_length=200)),
                ("account_number_masked", models.CharField(max_length=20)),
                (
                    "iban_masked",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("currency", models.CharField(default="USD", max_length=8)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "family_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_accounts",
                        to="family.familyaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "family bank account",
                "verbose_name_plural": "family bank accounts",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="FamilyTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("transaction_type", models.CharField(max_length=32)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bank_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="family.familybankaccount",
                    ),
                ),
                (
                    "family_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="family.familyaccount",
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="family_transactions_initiated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "family transaction",
                "verbose_name_plural": "family transactions",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="FamilyTransferSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("immediate", "Immediate"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("threshold", "Threshold"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "threshold_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                ("next_transfer_date", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="family.familybankaccount",
                    ),
                ),
                (
                    "family_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="family.familyaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "family transfer schedule",
                "verbose_name_plural": "family transfer schedules",
                "ordering": ("-created_at",),
            },
        ),
    ]
