# Generated by Django 5.2.15 on 2026-06-24 07:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distributions", "0001_initial"),
        ("family", "0001_initial"),
        ("wallets", "0005_deposit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FamilyAccrual",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[("accrual", "Accrual"), ("withdrawal", "Withdrawal")],
                        max_length=12,
                    ),
                ),
                ("amount_usd", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "allocation_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "owner_share_usd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("memo", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "distribution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="family_accruals",
                        to="distributions.distribution",
                    ),
                ),
                (
                    "family_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accruals",
                        to="family.familyaccount",
                    ),
                ),
                (
                    "investor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_accruals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_payout",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="family_accruals",
                        to="distributions.distributionpayout",
                    ),
                ),
                (
                    "withdrawal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="family_accruals",
                        to="wallets.withdrawal",
                    ),
                ),
            ],
            options={
                "verbose_name": "family accrual",
                "verbose_name_plural": "family accruals",
                "db_table": "family_accruals",
                "ordering": ("-created_at",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("distribution", "family_account"),
                        name="uniq_family_accrual_per_distribution_member",
                    )
                ],
            },
        ),
    ]
